# Generated by Django 2.0.5 on 2018-05-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('passwd', models.CharField(max_length=20, verbose_name='密码')),
                ('sex', models.BooleanField(default=1, verbose_name='性别')),
            ],
            options={
                'db_table': 'tb_student_info',
            },
        ),
    ]
