# Generated by Django 2.0.5 on 2018-05-22 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dept',
            table='tb_dept',
        ),
        migrations.AlterModelTable(
            name='emp',
            table='tb_emp',
        ),
    ]
