# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-23 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarInfo',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('car_id', models.CharField(max_length=7, verbose_name='车牌号')),
                ('pe_reason', models.CharField(max_length=100, verbose_name='违章原因')),
                ('pe_date', models.DateTimeField(verbose_name='违章日期')),
                ('punish', models.CharField(max_length=100, verbose_name='处罚方式')),
                ('accept', models.BooleanField(default=0, verbose_name='是否受理')),
            ],
            options={
                'db_table': 'tb_car_info',
            },
        ),
    ]
